OrdererOrgs:
  - Name: Orderer
    Domain: messanger.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.messanger.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.messanger.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Authority
    Domain: Authority.messanger.com
    Template:
      Count: 1
    Users:
      Count: 1
