docker exec cli.Authority bash -c 'peer channel create -c org1 -f ./channels/Org1.tx -o orderer.messanger.com:7050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'
docker exec cli.Authority bash -c 'peer channel create -c org2 -f ./channels/Org2.tx -o orderer.messanger.com:7050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'

docker exec cli.Authority bash -c 'peer channel join -b org1.block --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'
docker exec cli.Authority bash -c 'peer channel join -b org2.block --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'

docker exec cli0.Org1 bash -c 'peer channel join -b org1.block --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'
docker exec cli0.Org2 bash -c 'peer channel join -b org2.block --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'
docker exec cli1.Org1 bash -c 'peer channel join -b org1.block --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'
docker exec cli1.Org2 bash -c 'peer channel join -b org2.block --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'

docker exec cli0.Org1 bash -c 'peer channel update -o orderer.messanger.com:7050 -c org1 -f ./channels/org1anchor.tx --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'
docker exec cli0.Org2 bash -c 'peer channel update -o orderer.messanger.com:7050 -c org2 -f ./channels/org2anchor.tx --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'
docker exec cli.Authority bash -c 'peer channel update -o orderer.messanger.com:7050 -c org1 -f ./channels/Authanchororg1.tx --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'
docker exec cli.Authority bash -c 'peer channel update -o orderer.messanger.com:7050 -c org2 -f ./channels/Authanchororg2.tx --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'

docker exec cli0.Org1 bash -c 'peer chaincode install -p Authenticator -n Authenticator -v 0 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'
docker exec cli0.Org2 bash -c 'peer chaincode install -p Authenticator -n Authenticator -v 0 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'
docker exec cli.Authority bash -c 'peer chaincode install -p Authenticator -n Authenticator -v 0 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'
docker exec cli0.Org1 bash -c 'peer chaincode install -p Messanger -n Messanger -v 0 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'
docker exec cli0.Org2 bash -c 'peer chaincode install -p Messanger -n Messanger -v 0 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'
docker exec cli.Authority bash -c 'peer chaincode install -p Messanger -n Messanger -v 0 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem'

docker exec cli0.Org1 bash -c "peer chaincode instantiate -C org1 -n Authenticator -v 0 -c '{\"Args\":[]}' --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem"
docker exec cli0.Org2 bash -c "peer chaincode instantiate -C org2 -n Authenticator -v 0 -c '{\"Args\":[]}' --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem"
docker exec cli0.Org1 bash -c "peer chaincode instantiate -C org1 -n Messanger -v 0 -c '{\"Args\":[]}' --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem"
docker exec cli0.Org2 bash -c "peer chaincode instantiate -C org2 -n Messanger -v 0 -c '{\"Args\":[]}' --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/messanger.com/orderers/orderer.messanger.com/msp/tlscacerts/tlsca.messanger.com-cert.pem"
